<公式> ::= <原子命题> 
        | "¬" <公式> 
        | "(" <公式> <二元连接词> <公式> ")"
        | "TRUE"
        | "FALSE"

<原子命题> ::= <标识符>

<标识符> ::= <字母> | <标识符><字母> | <标识符><数字>

<字母> ::= "a" | "b" | ... | "z" | "A" | "B" | ... | "Z"

<数字> ::= "0" | "1" | ... | "9"

<二元连接词> ::= "∧" | "∨" | "→" | "↔"